{{- if .Values.externalSecret -}}
{{- range $key, $val := .Values.externalSecret }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $key }}
spec:
  backendType: secretsManager
  data:
    {{- range $env, $value := $val }}
    - key: {{ $key }}
      name: {{ $value }}
      property: {{ $value }}
      {{- if regexMatch "^NONBINARY_" $value }}
      isBinary: false
      {{ else if regexMatch "^BINARY_" $value }}
      isBinary: true
      {{ end }}
    {{- end }}
---
{{- end }}
{{- end }}
