{{- if .Values.externalSecret }}
{{- range $key, $val := .Values.externalSecret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: {{ $key }}
  {{- if $.Values.external_secrets.annotations }}
  annotations:
{{ toYaml $.Values.external_secrets.annotations | indent 4 }}
  {{- end }}
spec:
  data:
  {{- range $env, $value := $val }}
  - remoteRef: 
      key: {{ $key }}
      property: {{ $value }}
      {{- if regexMatch "^NONBINARY_" $value }}
      decodingStrategy: None
      {{- else if regexMatch "^BINARY_" $value }}
      decodingStrategy: Base64
      {{ end }}
    secretKey: {{ $value }}
    {{- end }}
  secretStoreRef:
    kind: {{ $.Values.external_secrets.secretStoreRef.kind }}
    name: {{ $.Values.external_secrets.secretStoreRef.name }}
---
{{- end }}
{{- end }}
