{{- if and .Values.rbac.enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "application.labels" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if $.Values.rbac.labels }}
{{ toYaml $.Values.rbac.labels | indent 4 }}
{{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" $ }}-role-{{ .name }}
rules:
{{ toYaml .rules | indent 2 }}
---
{{- end }}
{{- end }}