{{- if and .Values.rbac.enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
{{ include "application.labels" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if $.Values.rbac.labels }}
{{ toYaml $.Values.rbac.labels | indent 4 }}
{{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" $ }}-rb-{{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "application.name" $ }}-role-{{ .name }}
subjects:
  - kind: ServiceAccount
  {{- if $.Values.rbac.serviceAccount.name }}
    name: {{ $.Values.rbac.serviceAccount.name }}
  {{- else }}
    name: {{ template "application.name" $ }}
  {{- end }}
    namespace: {{ $.Release.Namespace }}
---
{{- end }}
{{- end }}
---
{{- if and .Values.rbac.enabled .Values.rbac.existingRoles }}
{{- range .Values.rbac.existingRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
{{ include "application.labels" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if $.Values.rbac.labels }}
{{ toYaml $.Values.rbac.labels | indent 4 }}
{{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" $ }}-rb-{{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .name }}
subjects:
  - kind: ServiceAccount
  {{- if $.Values.rbac.serviceAccount.name }}
    name: {{ $.Values.rbac.serviceAccount.name }}
  {{- else }}
    name: {{ template "application.name" $ }}
  {{- end }}
    namespace: {{ $.Release.Namespace }}
---
{{- end }}
{{- end }}