{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "application.labels" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.rbac.serviceAccount.labels }}
{{ toYaml .Values.rbac.serviceAccount.labels | indent 4 }}
{{- end }}
{{- if .Values.rbac.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.rbac.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- if .Values.rbac.serviceAccount.name }}
  name: {{ .Values.rbac.serviceAccount.name }}
{{- else }}
  name: {{ template "application.name" . }}
{{- end }}
{{- end }}
