{{- if ne .Values.environment "prod" -}}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-secrets-
  #name: sync-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      serviceAccountName: sync-secrets
      containers:
      - name: sync-secrets
        image: 768383028426.dkr.ecr.eu-central-1.amazonaws.com/pawapay-sync-secrets:2022_03_12_14_26_57
        args: []
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: github-creds
              key: username
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: github-creds
              key: token
        - name: SERVICE
          value: {{ template "application.name" . }}
        - name: ENVIRONMENT
          value: {{ .Values.environment }}
        - name: BRANCH
          value: "develop"
      restartPolicy: Never
  backoffLimit: 2

{{- end }}
